Update grouphug.mdx
yomorun/presence.js.org pull request #16
Opened 2024-01-02 06:41 UTC by murumury

Modify the document according to the README of the grouphug repo

2024-01-02 07:39 UTC, fanweixiao commented
looks like compile failed on Vercel, can you check `npm run build` locally?

2024-01-02 10:41 UTC, fanweixiao requested changes
please check vercel build error

2024-01-02 11:24 UTC, murumury commented
> please check vercel build error

done

2024-01-03 09:01 UTC, fanweixiao approved these changes

2024-01-03 09:02 UTC, merged